### ISSUE TITLE
Overwatch

### ISSUE THREAD

**Issue by CoolA1d** [DrNseven/D3D11-Worldtoscreen-Finder#1]
Hello,

When using this in Overwatch, the training bots reside in Stride 20. So I set it up to add models on stride 20, but the game crashes on this instruction:

if (FAILED(pDevice->CreateBuffer(&desc, NULL, &pStageBuffer)))

if I comment it out, it then crashes on this instruction:

HRESULT res = pContext->Map(pStageBuffer, 0, D3D11_MAP_READ, 0, &subRes);

and if I comment that line out along with the code that references it, then I crash on this line

pStageBuffer->GetDesc(&desc);

which is probably because res failed. 

Any help would be appreciated.

**Comment by CoolA1d** [comment]
Ok, I got past the CreateBuffer issue but I'm still crashing at Map...

**Comment by CoolA1d** [comment]
Nevermind, fixed both, however this still isn't working for Overwatch... I also changed ObjectCBNum to 7 and FrameCBNum to 9... still isn't working :/

**Comment by DrNseven** [comment]
Unfortunately I don't have overwatch and can't test anything there. Don't comment out Createbuffer, it is required. Try better model rec to avoid crashing. Make sure you only log the training bots and not other stuff with same Stride. Use Stride+ indesc.ByteWidth or IndexCount.
