### ISSUE TITLE
Label "Enemy" disapear sometimes for no reason

### ISSUE THREAD

**Issue by lgr20358** [DrNseven/D3D11-Worldtoscreen-Finder#10]
Hey there,

I made some modifications to try to find a solution but i'm stuck. Sometimes "Enemy" label disappear for a while. It can comeback but idk the reason.

I tried to move it there : 

if (Stride == 24 && Descr.Format == 71)
	{
		SetDepthStencilState(DISABLED);
		pContext->PSSetShader(psRed, NULL, NULL);
		phookD3D11DrawIndexed(pContext, IndexCount, StartIndexLocation, BaseVertexLocation);
		pContext->PSSetShader(psGreen, NULL, NULL);
		SetDepthStencilState(READ_NO_WRITE);
		AddModel(pContext);//w2s
	}

The AddModel. But seems like it's not changing at one moment the "clean" is forever...

**Comment by lgr20358** [comment]
Same issue with last update

**Comment by DrNseven** [comment]
new update fixed a crash bug. I'm not sure why esp disappears for some people, pretty sure it has to do with code in addmodel func, but don't see anything wrong

**Comment by lgr20358** [comment]
To be clear, it seems like the "aimheight" is moving a lot below you were used to see. i'll send you an example of what we see.

**Comment by lgr20358** [comment]
![image](https://user-images.githubusercontent.com/32402758/31056561-e15a469c-a6d3-11e7-8e2f-a01f6aae92bc.png)

Ok not necessary Below, sometimes it's on top. If you see my picture...

**Comment by lgr20358** [comment]
I switch on a lot of resolution, It seems like there is an issue on the calculation on "where do i have to put the label". So sometimes, this is working, but I can't figure which line I have to test for moving text

**Comment by lgr20358** [comment]
Sometimes, you can have 3 label for one person : 

![image](https://user-images.githubusercontent.com/32402758/31056913-4a7437e0-a6da-11e7-9f56-e3cbffea6743.png)

**Comment by DrNseven** [comment]
in fortnite you should filter out heads and only use those for aimbot to avoid some of these bugs, but I don't have values for heads for you

**Comment by lgr20358** [comment]
Ok let me know if you find it :) Do you think i have to play with the "stride" only ?

**Comment by lgr20358** [comment]
I think after searching for a while the best solution could me to create a function for refreshing every address, sounds like at one moment it has too many pointers or something like this.

**Comment by vadash** [comment]
I had this problem before updating injector (ye weird). I am running xenos with updated Blackbone
 lib. Xenos is opensourced
