### ISSUE TITLE
fixed aimbot

### ISSUE THREAD

**Issue by Astrallys** [DrNseven/D3D11-Worldtoscreen-Finder#11]
finish

**Comment by lgr20358** [comment]
source ?

**Comment by Kybertop** [comment]
Please how to use that source of D3D11 i have errors when i replace "?" to number what i need to do ?

**Comment by Astrallys** [comment]
which ? 
i haven't edit any ?

**Comment by Kybertop** [comment]
`if (Stride == ? && indesc.ByteWidth ? && indesc.ByteWidth ? && Descr.Format .. )` This but i replaced that "?" with number like 24

**Comment by Kybertop** [comment]
I need to know what i need to edit to make it working for Fortnite

**Comment by Astrallys** [comment]
i haven't edit any of those lines

**Comment by DrNseven** [comment]
try for better fps:
if(Stride == 24 && Descr.Format == 71 && pscdesc.ByteWidth == 4096)
you can also combine it with indesc.ByteWidth > value && indesc.ByteWidth < value

**Comment by Astrallys** [comment]
yep, no drops with that, still enemy word problem, need to find how to delete the top one

**Comment by xSk8eRx** [comment]
i cant see the link to download

**Comment by Kybertop** [comment]
I have only 1 Enemy.

**Comment by Kybertop** [comment]
And what i need to edit to full works with Fortnite ? Aimbot ESP CHAMS

**Comment by Astrallys** [comment]
do a CTRL ALT L ( change value ) then adjust with the 'insert" button

**Comment by Kybertop** [comment]
ok i do that but now i have that first -1 and i can't change that :/ everything works menu and text (not esp text but that bottom right)

**Comment by Kybertop** [comment]
[https://i.imgur.com/ER0PhrZ.jpg](url) here's image

**Comment by Kybertop** [comment]
Now it's working but it's lagging :/

**Comment by vadash** [comment]
Kybertop what ur cpu and gpu ? I am running it 75 fps on high distance low everything else
https://lh3.googleusercontent.com/-PbmmaDz-2Ps/WdN103y0hqI/AAAAAAAATNQ/60zP9jIrEyEOXnXlWzQYQmLTNn_1cHpigCHMYCw/s0/FortniteClient-Win64-Shipping_2017-10-03_14-34-39.jpg

**Comment by Kybertop** [comment]
i have the same options and i'm running it on 50 fps

**Comment by vadash** [comment]
And I run FX 6300 @ 4700 mhz. You running chams only, right ?

**Comment by Astrallys** [comment]
[d3d11hook.zip](https://github.com/DrNseven/D3D11-Worldtoscreen-Finder/files/1352745/d3d11hook.zip)
try this one

**Comment by Kybertop** [comment]
I have another aimbot with no recoil and no spread but with that i use only chams

**Comment by vadash** [comment]
[fortnitechampsonly.zip](https://github.com/DrNseven/D3D11-Worldtoscreen-Finder/files/1352764/fortnitechampsonly.zip)
or this one
