### ISSUE TITLE
cham color

### ISSUE THREAD

**Issue by Astrallys** [DrNseven/D3D11-Worldtoscreen-Finder#12]
Hey, where the line for changing the chams color ? ( can't find any color code for w2s)

**Comment by vadash** [comment]
if (!psRed)
GenerateShader(pDevice, &psRed, 1.0f, 0.0f, 0.0f);

**Comment by Astrallys** [comment]
not working, that's what i have change first

**Comment by vadash** [comment]
Replace
GenerateShader(pDevice, &psRed, 1.0f, 0.0f, 0.0f);
with
GenerateShader(pDevice, &psRed, 0.0f, 0.0f, 1.0f);

for example for blue

**Comment by Astrallys** [comment]
ohw, thanks. That's the point i have never know ahah. ( same for the colors, i just put random color ) 
i will see if the color can reduce the fps drops ( don't get any but some have so ) let's see
