### ISSUE TITLE
battleyes

### ISSUE THREAD

**Issue by Astrallys** [DrNseven/D3D11-Worldtoscreen-Finder#14]
does it is detected by battleyes games ? ( stupid question probably )

also how did you get it working with wwii ? my game keep crashing

**Comment by fwf02** [comment]
yes never play wwii so i cant tell you could be DrawIndexed  Virtualized or obfuscated   there  or you using Injection on user side (Ring3) and not kernel one (Ring0) try KeAttachProcess

**Comment by DragonQuestHero** [comment]
no.it's works 
![qq 20180930033839](https://user-images.githubusercontent.com/21189903/48256942-078b0980-e44c-11e8-9157-581c0fbeff14.jpg)

**Comment by hrt** [comment]
@DragonQuestHero  Did you get banned for this?
And did you modify how d3 is hooked in anyway

**Comment by DragonQuestHero** [comment]
@hrt no.nothing changed
i just inject dll to process.

**Comment by hrt** [comment]
> @hrt no.nothing changed
> i just inject dll to process.

Yes I did some changes and it worked fine on PUBG.
However, unmodified will not work on Fortnite

**Comment by DragonQuestHero** [comment]
> > @hrt no.nothing changed
> > i just inject dll to process.
> 
> Yes I did some changes and it worked fine on PUBG.
> However, unmodified will not work on Fortnite

i dont play Fortnite.
But I am very curious how about APEX.
and.i dont got banned.did u?

**Comment by hrt** [comment]
> > > @hrt no.nothing changed
> > > i just inject dll to process.
> > 
> > 
> > Yes I did some changes and it worked fine on PUBG.
> > However, unmodified will not work on Fortnite
> 
> i dont play Fortnite.
> But I am very curious how about APEX.
> and.i dont got banned.did u?

I haven't played games in a couple months - Apex wasn't released then so I can't say

**Comment by DragonQuestHero** [comment]
> > > > @hrt no.nothing changed
> > > > i just inject dll to process.
> > > 
> > > 
> > > Yes I did some changes and it worked fine on PUBG.
> > > However, unmodified will not work on Fortnite
> > 
> > 
> > i dont play Fortnite.
> > But I am very curious how about APEX.
> > and.i dont got banned.did u?
> 
> I haven't played games in a couple months - Apex wasn't released then so I can't say

me too..damn work busy
did u have telegram?maybe we can talk about bypass battleye inject

**Comment by hrt** [comment]
> > > > > @hrt no.nothing changed
> > > > > i just inject dll to process.
> > > > 
> > > > 
> > > > Yes I did some changes and it worked fine on PUBG.
> > > > However, unmodified will not work on Fortnite
> > > 
> > > 
> > > i dont play Fortnite.
> > > But I am very curious how about APEX.
> > > and.i dont got banned.did u?
> > 
> > 
> > I haven't played games in a couple months - Apex wasn't released then so I can't say
> 
> me too..damn work busy
> did u have telegram?maybe we can talk about bypass battleye inject

I abused trusted screen recording dlls with RWX sections of size zero with DMA to inject into any game.

https://www.unknowncheats.me/forum/anti-cheat-bypass/310607-change-x86-injector-inject-x64.html#post2302063

**Comment by DragonQuestHero** [comment]
> > > > > > @hrt no.nothing changed
> > > > > > i just inject dll to process.
> > > > > 
> > > > > 
> > > > > Yes I did some changes and it worked fine on PUBG.
> > > > > However, unmodified will not work on Fortnite
> > > > 
> > > > 
> > > > i dont play Fortnite.
> > > > But I am very curious how about APEX.
> > > > and.i dont got banned.did u?
> > > 
> > > 
> > > I haven't played games in a couple months - Apex wasn't released then so I can't say
> > 
> > 
> > me too..damn work busy
> > did u have telegram?maybe we can talk about bypass battleye inject
> 
> I abused trusted screen recording dlls with RWX sections of size zero with DMA to inject into any game.
> 
> https://www.unknowncheats.me/forum/anti-cheat-bypass/310607-change-x86-injector-inject-x64.html#post2302063

wait.DMA?like this?https://github.com/ufrisk/pcileech are u sure?lol
maybe i got new bypass.
but screen recording thread working.Hollowing and setcontext?
i patched loadimage callback to inject

**Comment by hrt** [comment]
> > > > > > > @hrt no.nothing changed
> > > > > > > i just inject dll to process.
> > > > > > 
> > > > > > 
> > > > > > Yes I did some changes and it worked fine on PUBG.
> > > > > > However, unmodified will not work on Fortnite
> > > > > 
> > > > > 
> > > > > i dont play Fortnite.
> > > > > But I am very curious how about APEX.
> > > > > and.i dont got banned.did u?
> > > > 
> > > > 
> > > > I haven't played games in a couple months - Apex wasn't released then so I can't say
> > > 
> > > 
> > > me too..damn work busy
> > > did u have telegram?maybe we can talk about bypass battleye inject
> > 
> > 
> > I abused trusted screen recording dlls with RWX sections of size zero with DMA to inject into any game.
> > https://www.unknowncheats.me/forum/anti-cheat-bypass/310607-change-x86-injector-inject-x64.html#post2302063
> 
> wait.DMA?like this?https://github.com/ufrisk/pcileech are u sure?lol
> maybe i got new bypass.
> but screen recording thread working.Hollowing and setcontext?
> i patched loadimage callback to inject

Yes DMA like that.

I do not use setcontext or anything. Just Read and Write to memory to steal control from the recording thread.
for example, if your screen recording software calls a function then place loop/jump at the line it returns to

If you can read and write to memory then you can inject by hijacking thread

**Comment by DragonQuestHero** [comment]
> > > > > > > > @hrt no.nothing changed
> > > > > > > > i just inject dll to process.
> > > > > > > 
> > > > > > > 
> > > > > > > Yes I did some changes and it worked fine on PUBG.
> > > > > > > However, unmodified will not work on Fortnite
> > > > > > 
> > > > > > 
> > > > > > i dont play Fortnite.
> > > > > > But I am very curious how about APEX.
> > > > > > and.i dont got banned.did u?
> > > > > 
> > > > > 
> > > > > I haven't played games in a couple months - Apex wasn't released then so I can't say
> > > > 
> > > > 
> > > > me too..damn work busy
> > > > did u have telegram?maybe we can talk about bypass battleye inject
> > > 
> > > 
> > > I abused trusted screen recording dlls with RWX sections of size zero with DMA to inject into any game.
> > > https://www.unknowncheats.me/forum/anti-cheat-bypass/310607-change-x86-injector-inject-x64.html#post2302063
> > 
> > 
> > wait.DMA?like this?https://github.com/ufrisk/pcileech are u sure?lol
> > maybe i got new bypass.
> > but screen recording thread working.Hollowing and setcontext?
> > i patched loadimage callback to inject
> 
> Yes DMA like that.
> 
> I do not use setcontext or anything. Just Read and Write to memory to steal control from the recording thread.
> for example, if your screen recording software calls a function then place loop/jump at the line it returns to
> 
> If you can read and write to memory then you can inject by hijacking thread

nice idea!
i will try.ths
actually,battleye protect memory on pubg very weak.
map new physical memory from virtual momory(mdl or iomapxxx) can easy bypass 
DMA to hard right ?lol

**Comment by schokoschwanz** [comment]
> no.it's works
> ![qq 20180930033839](https://user-images.githubusercontent.com/21189903/48256942-078b0980-e44c-11e8-9157-581c0fbeff14.jpg)

could u show ur settings to make it work in current pubg? even on countnum 76164 my model textures did not get invisible

i have working injector

**Comment by reddude256** [comment]
Can someone send me the Injector they used?

**Comment by 74263** [comment]
> > > > > > @hrt 没有任何改变，
> > > > > > 我只是注入 dll 进行处理。
> > > > > 
> > > > > 
> > > > > 是的，我做了一些更改，它在 PUBG 上运行良好。
> > > > > 但是，未经修改将不适用于 Fortnite
> > > > 
> > > > 
> > > > 我不玩堡垒之夜。
> > > > 但我很好奇 APEX 怎么样。
> > > > 而且。我没有被禁止。你呢？
> > > 
> > > 
> > > 我已经几个月没玩游戏了 - Apex 还没有发布，所以我不能说
> > 
> > 
> > 我也是..该死的工作很忙
> > 你有电报吗？也许我们可以谈谈绕过战斗注射
> 
> 我使用 DMA 滥用具有大小为零的 RWX 部分的受信任屏幕录制 dll 以注入任何游戏。
> 
> https://www.unknowncheats.me/forum/anti-cheat-bypass/310607-change-x86-injector-inject-x64.html#post2302063

Hey，could I ask how to use DMA to injection？
