### ISSUE TITLE
Knives Out does not work

### ISSUE THREAD

**Issue by x91270** [DrNseven/D3D11-Worldtoscreen-Finder#18]
InGame ：
![4jl98s456yj9fy s pzk 7](https://user-images.githubusercontent.com/7732205/34916179-c02bc2e6-f96e-11e7-8745-bba98b701b2b.png)

InRoom ：
![8 w 7ahaq 25f864 y3 h5](https://user-images.githubusercontent.com/7732205/34916178-b6966146-f96e-11e7-9764-56766a4e7c9e.png)

I found models Stride == 24

But other models that enter the game are also rendered

**Comment by DrNseven** [comment]
knives out is probably not ut4 engine or is a modified engine, try different matProjnum or other w2s

**Comment by x91270** [comment]
WorldViewCBnum
ProjCBnum
matProjnum

These have been debugged,

**Comment by x91270** [comment]
This game uses the Messiah engine

Netease company independent research and development
