### ISSUE TITLE
Chams - Yes, Text - Not working?

### ISSUE THREAD

**Issue by xzyxzy** [DrNseven/D3D11-Worldtoscreen-Finder#3]
Text not showing up for me at all, but chams are working after setting
worldview = 2
proj = 1
projnum = 16
countnum = 24
stride = 24

**Comment by DrNseven** [comment]
you mean w2s text is not working? Not sure, try injecting in main menu when you see your player

**Comment by xzyxzy** [comment]
Yeah, w2s has no text at all.
Sorry that issue was about old version but it is still present.
I've tried countless times in various stages of game, but, yeah, mostly in main menu wher my player is seen and play button is shown.
Also for some unknown reason as soon I started issue AND tried to update to latest version it now doesn't makes person in menu green with parts of red it makes them black (or very dark grey) and game crashes after to do anything (change settings, start match). I don't get it.
How it WAS working for me: https://vgy.me/fTrYAs.png
How it looks now: https://vgy.me/R29Zdb.png
Yes, same compiled dll it was.
After updating to latest version:
https://vgy.me/IEH8iU.png (black hair and stuff)

This is very weird.

**Comment by xzyxzy** [comment]
Tried pc reboot, still same. I swear it is patched or smth.
Also old version log file says this before crash

> Map stage buffer failed {1797552464} {512} {0} {131072} {3}
> CreateBuffer failed when CopyBufferToCpu {512}

**Comment by DrNseven** [comment]
that's strange, try this and let me know if it makes a difference

in main.h change these 3 to static:
static int WorldViewCBnum = 2;
static int ProjCBnum = 1;
static int matProjnum = 16;

remove these lines:
if (pWorldViewCB == NULL)
{
	SAFE_RELEASE(pWorldViewCB)
	//return; here only if a game is crashing
}

remove:
if (pProjCB == NULL)
{
	SAFE_RELEASE(pProjCB)
	//return; here only if a game is crashing
}

remove:
matWorldView[3][2] = matWorldView[3][2] + (aimheight * 20);	


remove shader generation code in universal.cpp, from hookD3D11Present:
//shaders
if (!psRed)
GenerateShader(pDevice, &psRed, 1.0f, 0.0f, 0.0f);

if (!psGreen)
GenerateShader(pDevice, &psGreen, 0.0f, 1.0f, 0.0f);

BUT paste/add the shader generation code in hookD3D11DrawIndexed

**Comment by xzyxzy** [comment]
Not sure if I did everything right.
I was editing current github version (black parts, but not whole).
It crashes few frames after trying to draw (i.e. shortly after injection). It manages to draw green almost on whole body, but face and hands.
Message in log

`Stride == 24 && IndexCount == 42606 && indesc.ByteWidth == 98388 && vedesc.ByteWidth == 252960 && texdesc.Format == 0 && Descr.Format == 0 && pscdesc.ByteWidth == 4096 && Descr.Buffer.NumElements == 0 && texdesc.Width == 0 && texdesc.Height == 0`

Could you take a look at what I'm ended up with? Current crash code with green drawings, already compiled dll of that, + previous dll with black hair.
https://a.pomf.cat/lrjnuk.rar

**Comment by DrNseven** [comment]
your code works for me, model turns green and I see white text under the model. Can you try another injector, maybe this? https://www.unknowncheats.me/forum/general-programming-and-reversing/213038-extreme-injector-v3-7-a.html

**Comment by xzyxzy** [comment]
I'm using exactly this injector from exactly this link.

**Comment by xzyxzy** [comment]
maybe options in game differs, I'm using windowed borderless, everything low but rendering resoution 1080p.

**Comment by xzyxzy** [comment]
Yay! It worked after I made it go fullscreen. Text working aswell!

**Comment by DrNseven** [comment]
good to hear, what happens if you change back to windowed? Btw. don't change resolution or it will crash.

**Comment by xzyxzy** [comment]
This is really weird, now borderless works. But everything I changed is options from borderless (at moment when it wasn't working) to fullscreen.

**Comment by xzyxzy** [comment]
Sorry for hassle and thanks!!!
