### ISSUE TITLE
Aimbot not working and Wallhack / ESP make players invisible / blurry in TABG

### ISSUE THREAD

**Issue by Kek5chen** [DrNseven/D3D11-Worldtoscreen-Finder#30]
Hey,

I dont know if i got the wrong settings but could you help me on which settings i should use to have this run on TABG? Or does it straight up not work?

If you have some time on your hand maybe we could discuss this further as im really interested in game / memory hacking and someone helping me out would make this alot easier.
Maybe you could contact me on Discord? `kx#0001` it is, if so i would appreciate it.

Have a nice day

**Comment by Kek5chen** [comment]
maybe you could proceed and give me the version of the dll's source you used in your video.?

**Comment by DrNseven** [comment]
Hi, it needs small changes, here is what I use: https://github.com/DrNseven/TAB-D3D11-Hack

**Comment by Kek5chen** [comment]
Awesome. I got it working. Forgot to change stuff in the main.h.

Do you plan on adding features to https://github.com/DrNseven/TAB-D3D11-Hack ? Like, health and stuff?

**Comment by Celllnside** [comment]
> Awesome. I got it working. Forgot to change stuff in the main.h.
> 
> Do you plan on adding features to https://github.com/DrNseven/TAB-D3D11-Hack ? Like, health and stuff?

hey, how do you start the menu do you use a injector or something?
