### ISSUE TITLE
start D3D11

### ISSUE THREAD

**Issue by Celllnside** [DrNseven/D3D11-Worldtoscreen-Finder#31]
how do i start D3D11 do i need to use in injector or something?

**Comment by Kek5chen** [comment]
You can easily inject a dll into the game by using SetWindowsHookEx. It bypasses EQU8 so it's perfect.

**Comment by Kek5chen** [comment]
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowshookexa Here is a reference from microsoft.

**Comment by Celllnside** [comment]
> https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowshookexa Here is a reference from microsoft.

i cant seem to set it up can you add me on discord and help me theres a few things i need help with my @ is Celllnside# 0001

**Comment by Celllnside** [comment]
> > https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowshookexa Here is a reference from microsoft.
> 
> i cant seem to set it up can you add me on discord and help me theres a few things i need help with my @ is Celllnside#1

#0001****

**Comment by Kek5chen** [comment]
This issue seems to be resolved in issue #32 . Please close this issue.
