### ISSUE TITLE
This is going to be a stupid question but here we go ( i don't know if you're alive )

### ISSUE THREAD

**Issue by notadaz** [DrNseven/D3D11-Worldtoscreen-Finder#34]
Anyway,

I'm stupid there is no doubt to that. 
I'm trying to get this in the form of an EXE, how would one do so.

(or a dll, I don't know how this works.)

**Comment by johnwill64** [comment]
> Anyway,
> 
> I'm stupid there is no doubt to that. I'm trying to get this in the form of an EXE, how would one do so.
> 
> (or a dll, I don't know how this works.)

You need to download Visual Studio and then open the file, "d3d11hook.vcxproj", in Visual Studio. Then on the top you see build, so press build solution when you hover on build. It will make a .dll called, "d3d11hook.dll", in the location you installed it. For example mine is this -> C:\Users\USERNAME\Documents\GitHub\D3D11-Worldtoscreen-Finder\x64\Release 
Then inject the d3d11hook.dll into the game and then edit the settings. That is the most that I have found out myself.

**Comment by notadaz** [comment]
> 

Thank you so much, that's now worked.

**Comment by notadaz** [comment]
What injector should I be using?
