### ISSUE TITLE
Help for fortnite

### ISSUE THREAD

**Issue by VVoXX** [DrNseven/D3D11-Worldtoscreen-Finder#4]
So i'm totally new to programming and have seen your post on UC... could you help me or send me the file to inject? i really didn't understand how this works... i have to open universal in visual studio and edit what? 
Stride == 24 ? and thats it? need help... Sorry if i'm stupid

**Comment by 3216alec** [comment]
your retarded

**Comment by 3216alec** [comment]
get good scrub

**Comment by WizardMan1337** [comment]
[what is visual studio? am i that retarded that i can't use google?](https://www.youtube.com/watch?v=QmZ6W5zjY3k)
[What i can google how to learn C++? who knew?](http://www.learncpp.com/)
You're Retarded
