### ISSUE TITLE
on off?

### ISSUE THREAD

**Issue by Astrallys** [DrNseven/D3D11-Worldtoscreen-Finder#6]
Hello,

First thanks for this, this help me a lot. I wanted to know how to put on/off fonction please.

I got aimbot working on the head ( not an advanced user ) so i can't switch between place. I search for on/off but found nothing.

Thanks

**Comment by DrNseven** [comment]
hi, uncomment //if ((sOptions[3].Function) || (sOptions[4].Function)) in universal.cpp, then you can toggle it on/off in menu. Menu key is insert, use arrows to navigate

**Comment by Astrallys** [comment]
thanks i will try that,  also find the correct code for aiming on the head if i can dm you :)

**Comment by DrNseven** [comment]
height is already there matWorldView[3][2] = matWorldView[3][2] + (aimheight * 20);
set it to 6 ingame using the menu

**Comment by Astrallys** [comment]
i use +(value ) and that aim correctly too. 
But thanks for this tip, i will try that

**Comment by Astrallys** [comment]
[d3d11hook[unknowncheats.me].dll.zip](https://github.com/DrNseven/D3D11-Worldtoscreen-Finder/files/1346377/d3d11hook.unknowncheats.me.dll.zip)
