### ISSUE TITLE
Aim stops 

### ISSUE THREAD

**Issue by Ovio224** [DrNseven/D3D11-Worldtoscreen-Finder#7]
Hi, 

The aim stops after like I'm trying to adjust it from the enemy height and aim sense.
The first time I press like RClick it goes crazy, then stable, then stops working.
Would that have a fix?

Thank you very much!

**Comment by Astrallys** [comment]
try aimheight 125 
and 
 matWorldView[3][2] = matWorldView[3][2] + (aimheight +125);

**Comment by Fertiwerd** [comment]
ya i have matWorldView[3][2] = matWorldView[3][2] + (aimheight +125); this however in game nothing works

**Comment by Ovio224** [comment]
Okay I have added the line and edited everything.

Everything works like a charm except the aimbot, it only aims on the "feet", where the tag "Enemy" is written.

Any fix for that? Thank you so much btw!

**Comment by Fertiwerd** [comment]
can you tell me how u got the enemy tag where did u put in the source code

**Comment by Ovio224** [comment]
Check out the other folders, not only universal.cpp :)
