### ISSUE TITLE
'argument': conversion from 'int' to 'FLOAT', possible loss of data

### ISSUE THREAD

**Issue by lgr20358** [DrNseven/D3D11-Worldtoscreen-Finder#9]
Hi,

I'm still having 2 warnings when I open your project 👍 

warning C4244: 'argument': conversion from 'int' to 'FLOAT', possible loss of data (line 206)
warning C4244: 'argument': conversion from 'float' to 'DWORD', possible loss of data (line 265)

Additionnally, scanner is not working (compiled with visual studio 2017) after injection.

Any idea ? I don't know what i'm doing wrong ...

**Comment by lgr20358** [comment]
![image](https://user-images.githubusercontent.com/32402758/31048838-6b0173e2-a626-11e7-9e28-9381fa4e53ec.png)

**Comment by lgr20358** [comment]
![image](https://user-images.githubusercontent.com/32402758/31048910-7e9e89ce-a628-11e7-93f4-3eadde055ae7.png)
All right, I added this :

	//bruteforce Coutnum
		if (GetAsyncKeyState('O') & 1) //-
			countnum--;
		if (GetAsyncKeyState('P') & 1) //+
			countnum++;
		if (GetAsyncKeyState(0x36) & 1) //6 reset, set to 0
			countnum = 0;
		if (countnum < 0)
			countnum = 0;

but this is still not working IG. Any idea ? this is really wierd...

**Comment by DrNseven** [comment]
You can ignore the warnings. I don't know why chams and stuff doesn't work for you, maybe drawindexed hook fails? Does anything turn red or green if you cycle through countnum 0 - 100?

**Comment by lgr20358** [comment]
Hello DrNseven, no, nothing seems to turn red or green between 0 - 100. I also tried on different game, same issue so this is probably coming from Visual Studio 2017...

![image](https://user-images.githubusercontent.com/32402758/31050557-8e1e8996-a64e-11e7-837b-8465732535d0.png)

**Comment by lgr20358** [comment]
I also tried to go on windows sdk 10 

![image](https://user-images.githubusercontent.com/32402758/31050562-b8eac2fc-a64e-11e7-8be6-ba7d4e6f8b3d.png)

Do you have any idea ? I'm so lost right now ...

**Comment by DrNseven** [comment]
compile in release mode, set configuration to release x64

**Comment by lgr20358** [comment]
It worked ! Thank you very much !!!
